routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('content');
});
Route::resource('mobil','CrudController');

app/Mobil.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mobil extends Model
{
    protected $primaryKey = 'NomorKendaraan';
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CrudController.php
<?php

namespace App\Http\Controllers;

use App\Mobil;
use Illuminate\Http\Request;

class CrudController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $mobil = new Mobil;
        $mobil->NomorKendaraan = $request->NomorKendaraan;
        $mobil->NomorPolisi = $request->NomorPolisi;
        $mobil->merek = $request->merek;
        $mobil->tipe = $request->tipe;
        $mobil->tahun = $request->tahun;
        $mobil->save();

       
       return 
       redirect('/');
       
       
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($NomorKendaraan)
    {
       Mobil::where($NomorKendaraan)->delete();
        return 
        redirect('/');
        
        //
    }
}

app/Http/Controllers/MobilController.php
<?php

namespace App\Http\Controllers;

use App\Mobil;
use Illuminate\Http\Request;

class MobilController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $mobil = Mobil::all();
        return response()->json(['data' => $mobil]);
        //
    }

    public function merek($merek)
    {
         $mobil = Mobil::where('merek',$merek)->first();
        return response()->json(['data' => $mobil]);
        //
    }

    public function type($merek, $tipe)
    {
         $mobil = Mobil::where(['merek' => $merek , 'tipe' => $tipe])->first();
        return response()->json(['data' => $mobil]);
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(request $request)
    {
        $mobil = new Mobil;
        $mobil->NomorKendaraan = $request->NomorKendaraan;
        $mobil->NomorPolisi = $request->NomorPolisi;
        $mobil->merek = $request->merek;
        $mobil->tipe = $request->tipe;
        $mobil->tahun = $request->tahun;
        $mobil->save();

        return "data berhasil masuk";
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Mobil  $mobil
     * @return \Illuminate\Http\Response
     */
    public function show(Mobil $mobil)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Mobil  $mobil
     * @return \Illuminate\Http\Response
     */
    public function edit(Mobil $mobil)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Mobil  $mobil
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Mobil $NomorKendaraan)
    {
        $mobil = Mobil::find($NomorKendaraan)->first();     
        $mobil->NomorKendaraan = $request->NomorKendaraan;
        $mobil->NomorPolisi = $request->NomorPolisi;
        $mobil->merek = $request->merek;
        $mobil->tipe = $request->tipe;
        $mobil->tahun = $request->tahun;
        $mobil->update();

        return "Data berhasil di update";
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Mobil  $mobil
     * @return \Illuminate\Http\Response
     */
    public function destroy(Mobil $NomorKendaraan)
    {
        $mobil = Mobil::find($NomorKendaraan)->first();     
        $mobil->delete();

        return "data Berhasil di hapus";
        //
    }

}

resources/views/content.blade.php
					@extends('home')
					@section('konten')
					<div class="row" id="cobaSaja">
						<div class="col-md-4">
							<!-- MULTI CHARTS -->
							<div class="panel">
								<div class="panel-heading">
									<h3 class="panel-title">Tambah Data</h3>
									<div class="right">
										<button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
										<button type="button" class="btn-remove"><i class="lnr lnr-cross"></i></button>
									</div>
								</div>
								<div class="panel-body">
									<form action="{{route('mobil.store')}}" method="POST">
									{{ csrf_field() }}
									<input type="number" class="form-control" placeholder="Nomor Kedaraan" name="NomorKendaraan" *required>
									<br>
									<input type="text" class="form-control" placeholder="Nomor Polisi" name="NomorPolisi" *required>
									<br>
									<input type="text" class="form-control" placeholder="Merek" name="merek" >
									<br>
									<input type="text" class="form-control" placeholder="Type" name="tipe" >
									<br>
									<input type="year" class="form-control" placeholder="Tahun" name="tahun" >
									<br>

									<input type="submit" class="btn btn-primary" name="submit" value="Tambah">
									</form>
								</div>
							</div>
							<!-- END MULTI CHARTS -->
						</div>
						<div class="col-md-8">
							<!-- RECENT PURCHASES -->
							<div class="panel">
								<div class="panel-heading">
									<h3 class="panel-title">Data Mobil</h3>
									<div class="right">
										<button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
										<button type="button" class="btn-remove"><i class="lnr lnr-cross"></i></button>
									</div>
								</div>
								<div class="panel-body no-padding">
									<table class="table table-hover table-striped ">
										<thead>
											<tr>
												<th>Order No.</th>
												<th>Name</th>
												<th>Amount</th>
												<th>Date &amp; Time</th>
												<th>Status</th>
											</tr>
										</thead>
										<tbody id="listKendaraan">
											<tr>

											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
					@endsection

					@section('script')
					<script>
						var listDataMobil = []
						var elTarget = document.getElementById("listKendaraan")
						var dataIndex = 0
						var dataRender = ""
						function loadData(item, dataIndex){
							// dataRender += "<tr> <td>" + item[dataIndex].NomorKendaraan + "</td> <td>" + item[dataIndex].NomorPolisi + "</td> <td>" + item[dataIndex].merek + "</td> <td>" + item[dataIndex].tipe + "</td> <td>" + item[dataIndex].tahun + "</td> <td><button class='btn btn-danger'>Delete</button></td> </tr>"
							dataRender += `
								<tr>
									<td>
										` + item[dataIndex].NomorKendaraan + `
									</td>

									
									<td>
										` + item[dataIndex].NomorPolisi + `
									</td>

									
									<td>
										` + item[dataIndex].merek + `
									</td>

									
									<td>
										` + item[dataIndex].tipe + `
									</td>

									
									<td>
										` + item[dataIndex].tahun + `
									</td>
									<td>
									 	<form action="{{route('mobil.destroy', '`+item[dataIndex].$NomorKendaraan+`')}}" method="post">
											{{ csrf_field() }}
											{{ method_field("DELETE")}}
											<button class="btn btn-danger" type="submit">Delete</button>
										</form>
									</td>
								</tr>
							`
						}

						$(document).ready(() => {
							$.ajax({
								type:"GET",
								dataType:"json",
								url:"http://localhost:8000/api/mobil/",
								success:function(data){
									listDataMobil = data.data
									console.log(listDataMobil.length)
									for(dataIndex = 0; dataIndex < listDataMobil.length; dataIndex++){
										loadData(listDataMobil, dataIndex)
										console.log("1")
									}
									
									elTarget.innerHTML = dataRender
								}
							})
						})
					</script>
					@endsection

resources/views/home.blade.php
<!doctype html>
<html lang="en">

<head>
	<title>Dashboard | Klorofil - Free Bootstrap Dashboard Template</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<!-- VENDOR CSS -->
	<link rel="stylesheet" href="assets/vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="assets/vendor/font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" href="assets/vendor/linearicons/style.css">
	<link rel="stylesheet" href="assets/vendor/chartist/css/chartist-custom.css">
	<!-- MAIN CSS -->
	<link rel="stylesheet" href="assets/css/main.css">
	<link rel="stylesheet" href="assets/css/style.css">
	<!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
	<link rel="stylesheet" href="assets/css/demo.css">
	<!-- GOOGLE FONTS -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
	<!-- ICONS -->
	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
	<link rel="icon" type="image/png" sizes="96x96" href="assets/img/favicon.png">

	<script src="assets/plugins/jquery/jquery.min.js"></script>
	{{-- <script src="assets/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="assets/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="assets/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script> --}}


</head>

<body>
	<!-- WRAPPER -->
	<div id="wrapper">
		<!-- NAVBAR -->
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="brand">
				<a href="index.html"><img src="assets/img/logo-dark.png" alt="Klorofil Logo" class="img-responsive logo"></a>
			</div>
			<div class="container-fluid">
				<div id="navbar-menu">
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="assets/img/user.png" class="img-circle" alt="Avatar"> <span>Samuel</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
							<ul class="dropdown-menu">
								<li><a href="#"><i class="lnr lnr-user"></i> <span>My Profile</span></a></li>
								<li><a href="#"><i class="lnr lnr-envelope"></i> <span>Message</span></a></li>
								<li><a href="#"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li>
								<li><a href="#"><i class="lnr lnr-exit"></i> <span>Logout</span></a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<!-- END NAVBAR -->
		
		<!-- MAIN -->
			<!-- MAIN CONTENT -->
			<div class="main-content">
				<div class="container-fluid" id="mainView">
					@yield('konten')

				</div>
			</div>
			<!-- END MAIN CONTENT -->
	
		<div class="clearfix"></div>
		<footer>
			<div class="container-fluid">
				<p class="copyright">&copy; 2017 <a href="https://www.themeineed.com" target="_blank">Theme I Need</a>. All Rights Reserved.</p>
			</div>
		</footer>
	</div>
	<!-- END WRAPPER -->
	<!-- Javascript -->

	@yield('script');
	<script src="assets/vendor/jquery/jquery.min.js"></script>
	<script src="assets/vendor/bootstrap/js/bootstrap.min.js"></script>
	<script src="assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js"></script>
	<script src="assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
	<script src="assets/vendor/chartist/js/chartist.min.js"></script>
	<script src="assets/scripts/klorofil-common.js"></script>
</body>
</html>